version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
      time: '08:00'
      timezone: Europe/Prague

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
      time: '08:00'
      timezone: Europe/Prague
